/* This file was autogenerated by src/scripts/contract-addresses.ts */
/* Document assembled based on FlareContractRegistry contract read from https://coston-api.flare.network/ext/C/rpc */

export const contractsCostonReadFromNode = true;

const CostonContractsAddressesArray = [
    {
        name: "FtsoRegistry",
        address: "0xf7Bbf40145C82Fca13011C783AaeCa6bD95fd652",
        chainId: 16,
    },
    {
        name: "StateConnector",
        address: "0x0c13aDA1C7143Cf0a0795FFaB93eEBb6FAD6e4e3",
        chainId: 16,
    },
    {
        name: "FlareDaemon",
        address: "0x1000000000000000000000000000000000000002",
        chainId: 16,
    },
    {
        name: "PriceSubmitter",
        address: "0x1000000000000000000000000000000000000003",
        chainId: 16,
    },
    {
        name: "InflationAllocation",
        address: "0xD11CB940C8375c119CAe7b8A75844ec35371F2E0",
        chainId: 16,
    },
    {
        name: "Inflation",
        address: "0x12d20f1b378cd8ee8dA4729262645EC62FD52307",
        chainId: 16,
    },
    {
        name: "Supply",
        address: "0x98D2B1835A8D4a7c9915Ca212bDb5AA259642fac",
        chainId: 16,
    },
    {
        name: "FtsoRewardManager",
        address: "0xfD36176C63dA52E783a347DE3544B0b44C7054a6",
        chainId: 16,
    },
    {
        name: "CleanupBlockNumberManager",
        address: "0xB50DAcdaA3Af02F8A0533902C117ADFC31A31Ccf",
        chainId: 16,
    },
    {
        name: "VoterWhitelister",
        address: "0xFAe0fd738dAbc8a0426F47437322b6d026A9FD95",
        chainId: 16,
    },
    {
        name: "WNat",
        address: "0x767b25A658E8FC8ab6eBbd52043495dB61b4ea91",
        chainId: 16,
    },
    {
        name: "GovernanceVotePower",
        address: "0xEb10E3a19Ae0e2564E2c86dBd89517fe7F24789d",
        chainId: 16,
    },
    {
        name: "GovernanceSettings",
        address: "0x183fAfF6997C98A812A3B98748Fc80241D08f312",
        chainId: 16,
    },
    {
        name: "AddressUpdater",
        address: "0xb006c0cb0b2b8ae48E5B12883Cd5a13654cc6e20",
        chainId: 16,
    },
    {
        name: "FtsoManager",
        address: "0x12B6E9dB4Ac9889aBb92beAA6CF7d71f334c1168",
        chainId: 16,
    },
    {
        name: "PollingFoundation",
        address: "0xe435D00D30DEc987Afd5dAC2205F2b20e2F90eB8",
        chainId: 16,
    },
    {
        name: "FlareContractRegistry",
        address: "0xaD67FE66660Fb8dFE9d6b1b4240d8650e30F6019",
        chainId: 16,
    },
    {
        name: "ClaimSetupManager",
        address: "0x3F55A3c8012C26B140AcC23d061E7c4626d64e01",
        chainId: 16,
    },
    {
        name: "FlareAssetRegistry",
        address: "0x92B87cc4205265e9500d570D452A3f7F91926e91",
        chainId: 16,
    },
    {
        name: "PollingFtso",
        address: "0xD036a8F254ef782cb93af4F829A1568E992c3864",
        chainId: 16,
    },
    {
        name: "Submission",
        address: "0x2cA6571Daa15ce734Bbd0Bf27D5C9D16787fc33f",
        chainId: 16,
    },
    {
        name: "EntityManager",
        address: "0x60A848E5Da796D741e559c170E851FC813061217",
        chainId: 16,
    },
    {
        name: "VoterRegistry",
        address: "0x051E9Cb16A8676C011faa10efA1ABE95372e7825",
        chainId: 16,
    },
    {
        name: "FlareSystemsCalculator",
        address: "0x43CBAB9C953F54533aadAf7ffCD13c30ec05Edc9",
        chainId: 16,
    },
    {
        name: "FlareSystemsManager",
        address: "0x85680Dd93755Fe5d0789773fd0896cEE51F9e358",
        chainId: 16,
    },
    {
        name: "RewardManager",
        address: "0xA17197b7Bdff7Be7c3Da39ec08981FB716B70d3A",
        chainId: 16,
    },
    {
        name: "Relay",
        address: "0x32D46A1260BB2D8C9d5Ab1C9bBd7FF7D7CfaabCC",
        chainId: 16,
    },
    {
        name: "WNatDelegationFee",
        address: "0xD6f2DC0A3433613d3d0Ee1d764e22631cCF175C8",
        chainId: 16,
    },
    {
        name: "FtsoInflationConfigurations",
        address: "0x4f634084483dE74cd4b69007fdF1DaeCC7354991",
        chainId: 16,
    },
    {
        name: "FtsoRewardOffersManager",
        address: "0xC9534cB913150aD3e98D792857689B55e2404212",
        chainId: 16,
    },
    {
        name: "FtsoFeedDecimals",
        address: "0x2A58AaD06CbEc8Dd23004fCCefA53e86dDFA64c3",
        chainId: 16,
    },
    {
        name: "FtsoFeedPublisher",
        address: "0x595AbCc4f9330b30ca31966dFfF71EBE0Af2b820",
        chainId: 16,
    },
    {
        name: "FtsoFeedIdConverter",
        address: "0x5c871668b17B604c0CAA848D8Efa7D9094748BC8",
        chainId: 16,
    },
];

export const deployedContractsCoston = [
    "FtsoRegistry",
    "StateConnector",
    "FlareDaemon",
    "PriceSubmitter",
    "InflationAllocation",
    "Inflation",
    "Supply",
    "FtsoRewardManager",
    "CleanupBlockNumberManager",
    "VoterWhitelister",
    "WNat",
    "GovernanceVotePower",
    "GovernanceSettings",
    "AddressUpdater",
    "FtsoManager",
    "PollingFoundation",
    "FlareContractRegistry",
    "ClaimSetupManager",
    "FlareAssetRegistry",
    "PollingFtso",
    "Submission",
    "EntityManager",
    "VoterRegistry",
    "FlareSystemsCalculator",
    "FlareSystemsManager",
    "RewardManager",
    "Relay",
    "WNatDelegationFee",
    "FtsoInflationConfigurations",
    "FtsoRewardOffersManager",
    "FtsoFeedDecimals",
    "FtsoFeedPublisher",
    "FtsoFeedIdConverter",
] as const;

export const CostonContractsAddresses = new Map(
    CostonContractsAddressesArray.map((i) => [i.name, i])
);
