/* This file was autogenerated by src/scripts/contract-addresses.ts */
/* Document assembled based on FlareContractRegistry contract read from https://coston2-api.flare.network/ext/C/rpc */

export const contractsCoston2ReadFromNode = true;

const Coston2ContractsAddressesArray = [
    {
        name: "StateConnector",
        address: "0x1000000000000000000000000000000000000001",
        chainId: 114,
    },
    {
        name: "FlareDaemon",
        address: "0x1000000000000000000000000000000000000002",
        chainId: 114,
    },
    {
        name: "PriceSubmitter",
        address: "0x1000000000000000000000000000000000000003",
        chainId: 114,
    },
    {
        name: "DistributionTreasury",
        address: "0x062b351bdBF365B51dd34bC25c8eDe43100E4cbC",
        chainId: 114,
    },
    {
        name: "IncentivePoolTreasury",
        address: "0x1000000000000000000000000000000000000005",
        chainId: 114,
    },
    {
        name: "InitialAirdrop",
        address: "0x8fB61aAbd150D2A236202Acc3F2CAFbf0aB41166",
        chainId: 114,
    },
    {
        name: "GovernanceSettings",
        address: "0x1000000000000000000000000000000000000007",
        chainId: 114,
    },
    {
        name: "AddressUpdater",
        address: "0x707C840D053f28DF75223C151fA7aFa6d7eB3354",
        chainId: 114,
    },
    {
        name: "InflationAllocation",
        address: "0xfa1903401A0cf7048A94C63D5dc5B4f36ff7b176",
        chainId: 114,
    },
    {
        name: "Inflation",
        address: "0x98B8e9B5830F04Fe3b8d56A2f8455E337037ba28",
        chainId: 114,
    },
    {
        name: "Supply",
        address: "0x0496dcb45cDf498e3b797050f0469a0DE24F02e9",
        chainId: 114,
    },
    {
        name: "FtsoRewardManager",
        address: "0x16E6A0b7a26518c336Bca0E935782C22A9EE07Fd",
        chainId: 114,
    },
    {
        name: "CleanupBlockNumberManager",
        address: "0xEaA8968E9B70dd2559066E3e801Df1596a4CFA23",
        chainId: 114,
    },
    {
        name: "FtsoRegistry",
        address: "0x48Da21ce34966A64E267CeFb78012C0282D0Ac87",
        chainId: 114,
    },
    {
        name: "VoterWhitelister",
        address: "0xa497f1Ed4edeA8151fECe457aa26e1D6A4318B6A",
        chainId: 114,
    },
    {
        name: "DistributionToDelegators",
        address: "0xbd33bDFf04C357F7FC019E72D0504C24CF4Aa010",
        chainId: 114,
    },
    {
        name: "IncentivePoolAllocation",
        address: "0xfaf3bDB0c455ef633A0B61E9424bcbC75FfaE29a",
        chainId: 114,
    },
    {
        name: "IncentivePool",
        address: "0x6892bDbBb14e1c9bD46Bf31E7BaC94d038fc82a6",
        chainId: 114,
    },
    {
        name: "FtsoManager",
        address: "0x4F52e61907B0ED9f26b88F16B2510a4CA524d6d0",
        chainId: 114,
    },
    {
        name: "WNat",
        address: "0xC67DCE33D7A8efA5FfEB961899C73fe01bCe9273",
        chainId: 114,
    },
    {
        name: "GovernanceVotePower",
        address: "0x8e4A2c063E1C82C9f5cb96489c0d2b6d78dF0538",
        chainId: 114,
    },
    {
        name: "ClaimSetupManager",
        address: "0x5Ddb590530EF66775E6225671eaBD94959e9AE0e",
        chainId: 114,
    },
    {
        name: "ValidatorRewardManager",
        address: "0x33913AcE907F682E305f36d7538D3cCd37E2cA5B",
        chainId: 114,
    },
    {
        name: "PollingFoundation",
        address: "0x48a59E8F8f29dA3dD1C2C2Fe54209f219535BFBA",
        chainId: 114,
    },
    {
        name: "FlareAssetRegistry",
        address: "0xC79E6Dc1817DddcB4206a0aDbb56832F476F4b67",
        chainId: 114,
    },
    {
        name: "Escrow",
        address: "0x05ad5ABCA6738f94C7b6CdFd9Da7E47F34966F01",
        chainId: 114,
    },
    {
        name: "ValidatorRegistry",
        address: "0x4CDEBD06352B3eB6e3Eec31Be70aB8931De46Ffe",
        chainId: 114,
    },
    {
        name: "CombinedNat",
        address: "0xa9ef58F5CFf9e282d759e36b249011729a74E7dd",
        chainId: 114,
    },
    {
        name: "FlareContractRegistry",
        address: "0xaD67FE66660Fb8dFE9d6b1b4240d8650e30F6019",
        chainId: 114,
    },
    {
        name: "PollingFtso",
        address: "0x501A498e8FDA589038d6526C2153a9fdc9d8eDD2",
        chainId: 114,
    },
    {
        name: "AddressBinder",
        address: "0x332aa9e37D64CAAF70ae5dBe8EFC2FC7611934Ae",
        chainId: 114,
    },
    {
        name: "PChainStakeMirror",
        address: "0xd2a1Bb23eB350814a30Dd6f9de78Bb2C8fdD9F1D",
        chainId: 114,
    },
    {
        name: "PChainStakeMirrorVerifier",
        address: "0xd61d6bEfB3B5C3e1D13b43C46CC1cebA3505a7aF",
        chainId: 114,
    },
    {
        name: "PChainStakeMirrorMultiSigVoting",
        address: "0x37c5d6DCCb4421A47E3931584B306fBc00288aE9",
        chainId: 114,
    },
];

export const deployedContractsCoston2 = [
    "StateConnector",
    "FlareDaemon",
    "PriceSubmitter",
    "DistributionTreasury",
    "IncentivePoolTreasury",
    "InitialAirdrop",
    "GovernanceSettings",
    "AddressUpdater",
    "InflationAllocation",
    "Inflation",
    "Supply",
    "FtsoRewardManager",
    "CleanupBlockNumberManager",
    "FtsoRegistry",
    "VoterWhitelister",
    "DistributionToDelegators",
    "IncentivePoolAllocation",
    "IncentivePool",
    "FtsoManager",
    "WNat",
    "GovernanceVotePower",
    "ClaimSetupManager",
    "ValidatorRewardManager",
    "PollingFoundation",
    "FlareAssetRegistry",
    "Escrow",
    "ValidatorRegistry",
    "CombinedNat",
    "FlareContractRegistry",
    "PollingFtso",
    "AddressBinder",
    "PChainStakeMirror",
    "PChainStakeMirrorVerifier",
    "PChainStakeMirrorMultiSigVoting",
] as const;

export const Coston2ContractsAddresses = new Map(
    Coston2ContractsAddressesArray.map((i) => [i.name, i])
);
