/* This file was autogenerated by src/scripts/contract-addresses.ts */
/* Document assembled based on FlareContractRegistry contract read from null */

export const contractsFlareReadFromNode = false;

export const deployedContractsFlare = [] as const;

export const FlareContractsAddresses = new Map();
