/* This file was autogenerated by src/scripts/contract-addresses.ts */
/* Document assembled based on FlareContractRegistry contract read from null */

export const contractsSongbirdReadFromNode = false;

export const deployedContractsSongbird = [] as const;

export const SongbirdContractsAddresses = new Map();
